apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c1pay-ingress
  namespace: c1pay
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/CERT_ID   # replace
    alb.ingress.kubernetes.io/manage-shared-policies: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - c1pay.yourdomain.com      # replace with your domain
      secretName: c1pay-tls
  defaultBackend:
    service:
      name: c1pay
      port:
        number: 80
