apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c1pay-ingress
  namespace: c1pay
  annotations:
    # Traefik v2 — HTTP (no TLS for now)
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  defaultBackend:
    service:
      name: c1pay
      port:
        number: 80
